name: Python Vulnerability Scanner - pip-audit
description: pip-audit Dependency SAST scanner for Python
inputs:
  requirements-file:
    description: requirements.txt to audit
    required: false
    default: requirements.txt
runs:
  using: docker
  image: Dockerfile
  args: [
    "--requirements-file", "${{ inputs.requirements-file }}", "--ignore-vuln", "PYSEC-2023-73"
  ]
