on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
        default: "./Dockerfile"
      context:
        type: string
        required: false
        default: "."
      image-name:
        type: string
        required: false
        default: ""
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      snyk-token:
        required: false
    outputs:
      image:
        value: ${{ jobs.dockerize.outputs.image }}

name: "Dockerize Application"

jobs:
  dockerize:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    outputs:
      image: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
    steps:
    - uses: actions/checkout@v4

    - name: Connect to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ secrets.registry-username }}
        password: ${{ secrets.registry-password }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64
        tags: ${{ inputs.registry-url }}/${{ inputs.image-name || github.repository }}:${{ github.sha }}

    - name: Upload Docker image to ${{ inputs.registry-url }}
      run: |
        docker push ${{ inputs.registry-url }}/${{ inputs.image-name || github.repository }}:${{ github.sha }}

  scan-docker-image:
    needs:
    - dockerize

    uses: ./.github/workflows/docker-sast.yaml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
      registry-url: ${{ inputs.registry-url }}
    secrets:
      registry-username: ${{ secrets.registry-username }}
      registry-password: ${{ secrets.registry-password }}
