on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        required: true
      image:
        type: string
        required: true
      registry-url:
        type: string
        required: true
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      snyk-token:
        required: true

name: "Run SAST for Docker image"

jobs:
  grype:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Connect to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      
      - name: Run Grype to check Docker image for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.registry-url }}/${{ inputs.image }}
          severity-cutoff: high
          output-format: table

  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: "snyk/snyk:docker"

    env:
      SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
      SNYK_INTEGRATION_VERSION: docker
      SNYK_TOKEN: "${{ secrets.snyk-token }}"

    permissions:
      actions: read
      contents: read
      statuses: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Connect to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk container test --severity-threshold=medium --file="${{ inputs.dockerfile }}" --policy-path=".snyk" "${{ inputs.registry-url }}/${{ inputs.image }}"
