on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        required: true
      image:
        type: string
        required: true
      registry-url:
        type: string
        required: true
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      snyk-token:
        required: false
          
name: "Run SAST for Docker image"

jobs:
  grype:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Connect to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ secrets.registry-username }}
        password: ${{ secrets.registry-password }}

    - name: Run Grype to check Docker image for vulnerabilities
      id: grype_scan
      uses: anchore/scan-action@v3
      with:
        image: ${{ inputs.registry-url }}/${{ inputs.image }}
        severity-cutoff: high
        output-format: sarif

    # TODO: Uncomment this once we GAS
    # - name: upload Anchore scan SARIF report
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: ${{ steps.grype_scan.outputs.sarif }}