on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
        default: "./Dockerfile"
      context:
        type: string
        required: false
        default: "."
      image-name:
        type: string
        required: false
        default: ""
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      snyk-token:
        required: true
    outputs:
      image:
        value: ${{ jobs.dockerize.outputs.image }}

name: "Dockerize Application"

jobs:
  dockerize:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    outputs:
      image: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v3

      - name: Connect to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64
          tags: ${{ inputs.registry-url }}/${{ inputs.image-name || github.repository }}:${{ github.sha }}
          outputs: type=docker,dest=/tmp/${{ inputs.image-name || github.repository }}:${{ github.sha }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
          path: /tmp/${{ inputs.image-name || github.repository }}:${{ github.sha }}.tar

  scan-docker-image:
    needs:
      - dockerize
    uses: ./.github/workflows/docker-sast.yaml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
      registry-url: ${{ inputs.registry-url }}
    secrets:
      snyk-token: ${{ secrets.snyk-token }}


  push-docker-image:
    needs: scan-docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.image-name || github.repository }}:${{ github.sha }}
        path: /tmp
    - name: Load image
      run: |
        docker load --input /tmp/${{ inputs.image-name || github.repository }}:${{ github.sha }}.tar
    - name: Upload Docker image to ${{ inputs.registry-url }}
      run: |
        docker push ${{ inputs.registry-url }}/${{ inputs.image-name || github.repository }}:${{ github.sha }}