on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: true
      snyk-test:
        type: boolean
        required: false
        default: false
      snyk-code:
        type: boolean
        required: false
        default: false
    secrets:
      nuget-token:
        required: false
      snyk-token:
        required: false

name: "Run SAST for .NET"

jobs:
  package-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      
      - name: Configure NuGet for private packages
        run: |
          [ ! -z "${{ secrets.nuget-token }}" ] && dotnet nuget update source "wayke-gh" --store-password-in-clear-text --configfile NuGet.Config -u "ourbjorn" -p "${{ secrets.nuget-token }}" || true

      - name: Download dependencies
        run: |
          dotnet restore

      - name: Run package scanner
        run: |
          RESULT=$(dotnet list package --vulnerable --include-transitive)
          echo "${RESULT}"
          test $(echo "${RESULT}" | grep -cm 1 "following vulnerable packages") -ne 1
