on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: true
      snyk-test:
        type: boolean
        required: false
        default: false
      snyk-code:
        type: boolean
        required: false
        default: false
    secrets:
      go-token:
        required: false
      snyk-token:
        required: false

name: "Run SAST for Go"

jobs:
  go-vet:
    runs-on: ubuntu-8cpu
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure git for private modules
      run: |
        [ ! -z "${{ secrets.go-token }}" ] && git config --global url."https://${{ secrets.go-token }}@github.com".insteadOf "https://github.com" || true

    - name: Download dependencies
      run: |
        go mod download

    - name: Run go-vet
      run: |
        go vet ./...

  golangci-lint:
    runs-on: ubuntu-8cpu
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure git for private modules
      run: |
        [ ! -z "${{ secrets.go-token }}" ] && git config --global url."https://${{ secrets.go-token }}@github.com".insteadOf "https://github.com" || true

    - name: Download dependencies
      run: |
        go mod download

    - name: Verify existence of config file
      run: |
        test -f .golangci.yml && mv .golangci.yml .golangci.yaml; test -f .golangci.yaml || printf "run:\n  timeout: 5m\n" > .golangci.yaml

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        skip-cache: true
        args: --config .golangci.yaml

  sonatype-nancy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure git for private modules
      run: |
        [ ! -z "${{ secrets.go-token }}" ] && git config --global url."https://${{ secrets.go-token }}@github.com".insteadOf "https://github.com" || true

    - name: Download dependencies
      run: |
        go mod download

    - name: Populate dependency file
      run: |
        go list -json -m all > go.list

    - name: Run nancy dependency scanner
      uses: wayke-se/ci/.github/actions/golang/sonatype-nancy@master
      with:
        file: go.list

  govulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure git for private modules
      run: |
        [ ! -z "${{ secrets.go-token }}" ] && git config --global url."https://${{ secrets.go-token }}@github.com".insteadOf "https://github.com" || true

    - name: Download dependencies
      run: |
        go mod download

    - name: Run govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
