on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      image:
        type: string
        required: true
      cluster:
        type: string
        required: true
      environment:
        type: string
        required: true
      kustomize:
        type: string
        required: true
      watch:
        type: boolean
        required: false
        default: false
      sentry-config-map:
        type: string
        required: false
    secrets:
      credentials:
        required: true

name: "Deploy dockerized application"

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Prepare deployment files
        run: |
          pushd deploy/base
          kustomize edit set image ${{ inputs.service }}="${{ inputs.image }}"
          popd

      - name: Set Sentry environment variables
        if: inputs.sentry-config-map
        run: |
          pushd ${{ inputs.kustomize }}
          kustomize edit add patch --kind ConfigMap --name ${{ inputs.sentry-config-map }} --patch "[\
              {\"op\": \"add\", \"path\": \"/data/SENTRY_RELEASE\", \"value\": \"${{ github.sha }}\"},\
              {\"op\": \"add\", \"path\": \"/data/SENTRY_ENVIRONMENT\", \"value\": \"${{ inputs.environment }}\"}\
            ]"
          popd

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.credentials }}

      - name: Connect to Azure Kubernetes Service
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ inputs.cluster }}
          resource-group: ${{ inputs.environment }}
          admin: "true"

      - name: Dry run Kustomize to verify deploy files
        run: |
          kubectl apply --dry-run=client --kustomize ${{ inputs.kustomize }}

      - name: Deploy to Azure Kubernetes Service
        run: |
          kubectl apply --kustomize ${{ inputs.kustomize }}

      - name: Watch rollout
        if: ${{ inputs.watch }}
        run: |
          # Auto-detect deployments from Kustomize output
          echo "Auto-detecting deployments from Kustomize..."
          DEPLOYMENTS=$(kubectl get -k ${{ inputs.kustomize }} -o json | jq -r '.items[] | select(.kind=="Deployment") | .metadata.name')
          
          if [ -z "$DEPLOYMENTS" ]; then
            echo "No deployments found in Kustomize output. Falling back to service name."
            kubectl rollout status deploy/${{ inputs.service }} --watch
          else
            for deployment in $DEPLOYMENTS; do
              echo "Watching rollout for deployment: $deployment"
              kubectl rollout status deploy/$deployment --watch
            done
          fi
