on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
    secrets:
      snyk-token:
        required: true

name: "Run SAST for NodeJS"

jobs:
  package-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run npm audit
        run: |
          npm audit --audit-level high --package-lock-only --omit=dev

  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: "snyk/snyk:dotnet"

    env:
      SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
      SNYK_INTEGRATION_VERSION: node
      SNYK_TOKEN: "${{ secrets.snyk-token }}"

    permissions:
      actions: read
      contents: read
      statuses: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --file=package.json --severity-threshold=high --policy-path=".snyk"

      - name: Run Snyk to check for code security issues
        run: |
          snyk code test --file=package.json --severity-threshold=high --policy-path=".snyk"
