on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
    secrets:
      snyk-token:
        required: false

name: "Run SAST for NodeJS"

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Install dependencies
        run: npm ci --ignore-scripts --force

      - name: Run npm audit
        run: |
          npm audit --audit-level high --package-lock-only --omit=dev
