on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
      registry-url:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
        default: "./Dockerfile"
      requirements-file:
        type: string
        required: false
        default: requirements.txt
      snyk-test:
        type: boolean
        required: false
        default: true
      snyk-code:
        type: boolean
        required: false
        default: true
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      snyk-token:
        required: true
    outputs:
      image:
        value: ${{ jobs.dockerize.outputs.image }}

name: "Dockerize Python Application"

jobs:
  scan-code:
    uses: ./.github/workflows/python-sast.yaml
    with:
      python-version: ${{ inputs.python-version }}
      requirements-file: ${{ inputs.requirements-file }}
      snyk-test: ${{ inputs.snyk-test }}
      snyk-code: ${{ inputs.snyk-code }}
    secrets:
      snyk-token: ${{ secrets.snyk-token }}

  dockerize:
    needs:
      - scan-code
    
    runs-on: ubuntu-latest
    timeout-minutes: 20

    outputs:
      image: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Connect to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64
          tags: ${{ inputs.registry-url }}/${{ github.repository }}:${{ github.sha }}

      - name: Upload Docker image to ${{ inputs.registry-url }}
        run: |
          docker push ${{ inputs.registry-url }}/${{ github.repository }}:${{ github.sha }}

  scan-docker-image:
    needs:
      - dockerize

    uses: ./.github/workflows/docker-sast.yaml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ github.repository }}:${{ github.sha }}
      registry-url: ${{ inputs.registry-url }}
    secrets:
      registry-username: ${{ secrets.registry-username }}
      registry-password: ${{ secrets.registry-password }}
      snyk-token: ${{ secrets.snyk-token }}
