on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      auth-token:
        required: true

name: "Create Sentry release"

jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.auth-token }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ github.event.repository.name }}
        with:
          environment: ${{ inputs.environment }}